//
// File generated by rootcint at Wed Oct  3 16:48:49 2012

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME srcdIGRootWriterDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "GRootWriterDict.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void GRootWriter_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void delete_GRootWriter(void *p);
   static void deleteArray_GRootWriter(void *p);
   static void destruct_GRootWriter(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::GRootWriter*)
   {
      ::GRootWriter *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::GRootWriter >(0);
      static ::ROOT::TGenericClassInfo 
         instance("GRootWriter", ::GRootWriter::Class_Version(), "./include/GRootWriter.h", 23,
                  typeid(::GRootWriter), DefineBehavior(ptr, ptr),
                  &::GRootWriter::Dictionary, isa_proxy, 4,
                  sizeof(::GRootWriter) );
      instance.SetDelete(&delete_GRootWriter);
      instance.SetDeleteArray(&deleteArray_GRootWriter);
      instance.SetDestructor(&destruct_GRootWriter);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::GRootWriter*)
   {
      return GenerateInitInstanceLocal((::GRootWriter*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::GRootWriter*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *GRootWriter::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *GRootWriter::Class_Name()
{
   return "GRootWriter";
}

//______________________________________________________________________________
const char *GRootWriter::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GRootWriter*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int GRootWriter::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::GRootWriter*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void GRootWriter::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GRootWriter*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *GRootWriter::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::GRootWriter*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void GRootWriter::Streamer(TBuffer &R__b)
{
   // Stream an object of class GRootWriter.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(GRootWriter::Class(),this);
   } else {
      R__b.WriteClassBuffer(GRootWriter::Class(),this);
   }
}

//______________________________________________________________________________
void GRootWriter::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class GRootWriter.
      TClass *R__cl = ::GRootWriter::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fFile", &fFile);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTelID", &fTelID);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fTree", &fTree);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "treeBaseName", (void*)&treeBaseName);
      R__insp.InspectMember("string", (void*)&treeBaseName, "treeBaseName.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fEventNumber", &fEventNumber);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPrimaryType", &fPrimaryType);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPrimaryEnergy", &fPrimaryEnergy);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fXcore", &fXcore);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fYcore", &fYcore);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fXcos", &fXcos);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fYcos", &fYcos);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fXsource", &fXsource);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fYsource", &fYsource);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDelay", &fDelay);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fTransit", &fTransit);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "bStoreDcos", &bStoreDcos);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fPE_photonX", &fPE_photonX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fPE_photonY", &fPE_photonY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fPE_DcosX", &fPE_DcosX);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fPE_DcosY", &fPE_DcosY);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fPE_time", &fPE_time);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fPE_wl", &fPE_wl);
}

namespace ROOT {
   // Wrapper around operator delete
   static void delete_GRootWriter(void *p) {
      delete ((::GRootWriter*)p);
   }
   static void deleteArray_GRootWriter(void *p) {
      delete [] ((::GRootWriter*)p);
   }
   static void destruct_GRootWriter(void *p) {
      typedef ::GRootWriter current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::GRootWriter

namespace ROOT {
   void vectorlEfloatgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEfloatgR_Dictionary();
   static void *new_vectorlEfloatgR(void *p = 0);
   static void *newArray_vectorlEfloatgR(Long_t size, void *p);
   static void delete_vectorlEfloatgR(void *p);
   static void deleteArray_vectorlEfloatgR(void *p);
   static void destruct_vectorlEfloatgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<float>*)
   {
      vector<float> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<float>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<float>", -2, "vector.dll", 0,
                  typeid(vector<float>), DefineBehavior(ptr, ptr),
                  0, &vectorlEfloatgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<float>) );
      instance.SetNew(&new_vectorlEfloatgR);
      instance.SetNewArray(&newArray_vectorlEfloatgR);
      instance.SetDelete(&delete_vectorlEfloatgR);
      instance.SetDeleteArray(&deleteArray_vectorlEfloatgR);
      instance.SetDestructor(&destruct_vectorlEfloatgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<float> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<float>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEfloatgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<float>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEfloatgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<float> : new vector<float>;
   }
   static void *newArray_vectorlEfloatgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<float>[nElements] : new vector<float>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEfloatgR(void *p) {
      delete ((vector<float>*)p);
   }
   static void deleteArray_vectorlEfloatgR(void *p) {
      delete [] ((vector<float>*)p);
   }
   static void destruct_vectorlEfloatgR(void *p) {
      typedef vector<float> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<float>

/********************************************************
* src/GRootWriterDict.cpp
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableGRootWriterDict();

extern "C" void G__set_cpp_environmentGRootWriterDict() {
  G__cpp_reset_tagtableGRootWriterDict();
}
#include <new>
extern "C" int G__cpp_dllrevGRootWriterDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* GRootWriter */
static int G__GRootWriterDict_545_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GRootWriter* p = NULL;
   char* gvp = (char*) G__getgvp();
   switch (libp->paran) {
   case 5:
     //m: 5
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GRootWriter(
(TFile*) G__int(libp->para[0]), *(unsigned int*) G__UIntref(&libp->para[1])
, *(string*) libp->para[2].ref, *(bool*) G__Boolref(&libp->para[3])
, *(unsigned int*) G__UIntref(&libp->para[4]));
     } else {
       p = new((void*) gvp) GRootWriter(
(TFile*) G__int(libp->para[0]), *(unsigned int*) G__UIntref(&libp->para[1])
, *(string*) libp->para[2].ref, *(bool*) G__Boolref(&libp->para[3])
, *(unsigned int*) G__UIntref(&libp->para[4]));
     }
     break;
   case 4:
     //m: 4
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GRootWriter(
(TFile*) G__int(libp->para[0]), *(unsigned int*) G__UIntref(&libp->para[1])
, *(string*) libp->para[2].ref, *(bool*) G__Boolref(&libp->para[3]));
     } else {
       p = new((void*) gvp) GRootWriter(
(TFile*) G__int(libp->para[0]), *(unsigned int*) G__UIntref(&libp->para[1])
, *(string*) libp->para[2].ref, *(bool*) G__Boolref(&libp->para[3]));
     }
     break;
   case 3:
     //m: 3
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new GRootWriter(
(TFile*) G__int(libp->para[0]), *(unsigned int*) G__UIntref(&libp->para[1])
, *(string*) libp->para[2].ref);
     } else {
       p = new((void*) gvp) GRootWriter(
(TFile*) G__int(libp->para[0]), *(unsigned int*) G__UIntref(&libp->para[1])
, *(string*) libp->para[2].ref);
     }
     break;
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GRootWriterDictLN_GRootWriter));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 4:
      ((GRootWriter*) G__getstructoffset())->addPhoton(*(ROOT::Math::XYZVector*) libp->para[0].ref, *(ROOT::Math::XYZVector*) libp->para[1].ref
, *(double*) G__Doubleref(&libp->para[2]), *(double*) G__Doubleref(&libp->para[3]));
      G__setnull(result7);
      break;
   case 3:
      ((GRootWriter*) G__getstructoffset())->addPhoton(*(ROOT::Math::XYZVector*) libp->para[0].ref, *(ROOT::Math::XYZVector*) libp->para[1].ref
, *(double*) G__Doubleref(&libp->para[2]));
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((GRootWriter*) G__getstructoffset())->addEvent(
*(unsigned int*) G__UIntref(&libp->para[0]), *(unsigned int*) G__UIntref(&libp->para[1])
, *(double*) G__Doubleref(&libp->para[2]), *(ROOT::Math::XYZVector*) libp->para[3].ref
, *(ROOT::Math::XYZVector*) libp->para[4].ref, *(double*) G__Doubleref(&libp->para[5])
, *(double*) G__Doubleref(&libp->para[6]), *(double*) G__Doubleref(&libp->para[7])
, *(double*) G__Doubleref(&libp->para[8])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((GRootWriter*) G__getstructoffset())->getDataTree());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GRootWriter*) G__getstructoffset())->write();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 104, (long) ((GRootWriter*) G__getstructoffset())->getTelID());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GRootWriter*) G__getstructoffset())->cdToWriteRootFile();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) GRootWriter::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GRootWriter::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) GRootWriter::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      GRootWriter::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((const GRootWriter*) G__getstructoffset())->IsA());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GRootWriter*) G__getstructoffset())->ShowMembers(*(TMemberInspector*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GRootWriter*) G__getstructoffset())->Streamer(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((GRootWriter*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GRootWriter::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GRootWriter::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) GRootWriter::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__GRootWriterDict_545_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) GRootWriter::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__GRootWriterDict_545_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   GRootWriter* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new GRootWriter(*(GRootWriter*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__GRootWriterDictLN_GRootWriter));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef GRootWriter G__TGRootWriter;
static int G__GRootWriterDict_545_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 0
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (GRootWriter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((GRootWriter*) (soff+(sizeof(GRootWriter)*i)))->~G__TGRootWriter();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (GRootWriter*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((GRootWriter*) (soff))->~G__TGRootWriter();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__GRootWriterDict_545_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   GRootWriter* dest = (GRootWriter*) G__getstructoffset();
   *dest = *(GRootWriter*) libp->para[0].ref;
   const GRootWriter& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* GRootWriter */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncGRootWriterDict {
 public:
  G__Sizep2memfuncGRootWriterDict(): p(&G__Sizep2memfuncGRootWriterDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncGRootWriterDict::*p)();
};

size_t G__get_sizep2memfuncGRootWriterDict()
{
  G__Sizep2memfuncGRootWriterDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceGRootWriterDict() {

   /* Setting up class inheritance */
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableGRootWriterDict() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__GRootWriterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GRootWriterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GRootWriterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GRootWriterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GRootWriterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__GRootWriterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__GRootWriterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GRootWriterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__GRootWriterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__GRootWriterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__GRootWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__GRootWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__GRootWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__GRootWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__GRootWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__GRootWriterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__GRootWriterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__GRootWriterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__GRootWriterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* GRootWriter */
static void G__setup_memvarGRootWriter(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__GRootWriterDictLN_GRootWriter));
   { GRootWriter *p; p=(GRootWriter*)0x1000; if (p) { }
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GRootWriterDictLN_TFile),-1,-1,4,"fFile=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,4,"fTelID=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GRootWriterDictLN_TTree),-1,-1,4,"fTree=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__GRootWriterDictLN_string),-1,-1,4,"treeBaseName=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,4,"fEventNumber=",0,(char*)NULL);
   G__memvar_setup((void*)0,104,0,0,-1,-1,-1,4,"fPrimaryType=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"fPrimaryEnergy=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"fXcore=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"fYcore=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"fXcos=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"fYcos=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"fXsource=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"fYsource=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"fDelay=",0,(char*)NULL);
   G__memvar_setup((void*)0,102,0,0,-1,-1,-1,4,"fTransit=",0,(char*)NULL);
   G__memvar_setup((void*)0,103,0,0,-1,-1,-1,4,"bStoreDcos=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GRootWriterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"fPE_photonX=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GRootWriterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"fPE_photonY=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GRootWriterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"fPE_DcosX=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GRootWriterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"fPE_DcosY=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GRootWriterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"fPE_time=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GRootWriterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR),G__defined_typename("vector<float>"),-1,4,"fPE_wl=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__GRootWriterDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   G__memvar_setup((void*)0,108,0,0,-1,-1,-1,4,"G__virtualinfo=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarGRootWriterDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncGRootWriter(void) {
   /* GRootWriter */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__GRootWriterDictLN_GRootWriter));
   G__memfunc_setup("GRootWriter",1128,G__GRootWriterDict_545_0_1, 105, G__get_linked_tagnum(&G__GRootWriterDictLN_GRootWriter), -1, 0, 5, 1, 1, 0, 
"U 'TFile' - 0 - tfile h - - 11 - iTelID "
"u 'string' - 11 - treeBaseName g - - 11 'false' storePhotonDcos "
"h - - 11 '100000' iNInitEvents", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addPhoton",929,G__GRootWriterDict_545_0_2, 121, -1, -1, 0, 4, 1, 1, 0, 
"u 'ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<double>,ROOT::Math::DefaultCoordinateSystemTag>' 'ROOT::Math::XYZVector' 11 - PhotonCameraLoc u 'ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<double>,ROOT::Math::DefaultCoordinateSystemTag>' 'ROOT::Math::XYZVector' 11 - PhotonCameraDcos "
"d - - 11 - iPE_time d - - 11 '0.' iPE_wl", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("addEvent",811,G__GRootWriterDict_545_0_3, 105, -1, -1, 0, 9, 1, 1, 0, 
"h - - 11 - eventNumber h - - 11 - primaryType "
"d - - 11 - primaryEnergy u 'ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<double>,ROOT::Math::DefaultCoordinateSystemTag>' 'ROOT::Math::XYZVector' 11 - vSCore "
"u 'ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<double>,ROOT::Math::DefaultCoordinateSystemTag>' 'ROOT::Math::XYZVector' 11 - vSDCore d - - 11 - xSource "
"d - - 11 - ySource d - - 11 - delayTime "
"d - - 11 - transitTime", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getDataTree",1098,G__GRootWriterDict_545_0_4, 85, G__get_linked_tagnum(&G__GRootWriterDictLN_TTree), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("write",555,G__GRootWriterDict_545_0_5, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("getTelID",754,G__GRootWriterDict_545_0_6, 104, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("cdToWriteRootFile",1721,G__GRootWriterDict_545_0_7, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__GRootWriterDict_545_0_8, 85, G__get_linked_tagnum(&G__GRootWriterDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&GRootWriter::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__GRootWriterDict_545_0_9, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GRootWriter::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__GRootWriterDict_545_0_10, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&GRootWriter::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__GRootWriterDict_545_0_11, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&GRootWriter::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,G__GRootWriterDict_545_0_12, 85, G__get_linked_tagnum(&G__GRootWriterDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,G__GRootWriterDict_545_0_13, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,G__GRootWriterDict_545_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__GRootWriterDict_545_0_15, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__GRootWriterDict_545_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GRootWriter::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__GRootWriterDict_545_0_17, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GRootWriter::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__GRootWriterDict_545_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&GRootWriter::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__GRootWriterDict_545_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&GRootWriter::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("GRootWriter", 1128, G__GRootWriterDict_545_0_20, (int) ('i'), G__get_linked_tagnum(&G__GRootWriterDictLN_GRootWriter), -1, 0, 1, 1, 1, 0, "u 'GRootWriter' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~GRootWriter", 1254, G__GRootWriterDict_545_0_21, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 0);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__GRootWriterDict_545_0_22, (int) ('u'), G__get_linked_tagnum(&G__GRootWriterDictLN_GRootWriter), -1, 1, 1, 1, 1, 0, "u 'GRootWriter' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncGRootWriterDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalGRootWriterDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcGRootWriterDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__GRootWriterDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__GRootWriterDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__GRootWriterDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__GRootWriterDictLN_ROOT = { "ROOT" , 110 , -1 };
G__linked_taginfo G__GRootWriterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR = { "vector<float,allocator<float> >" , 99 , -1 };
G__linked_taginfo G__GRootWriterDictLN_string = { "string" , 99 , -1 };
G__linked_taginfo G__GRootWriterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__GRootWriterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GRootWriterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__GRootWriterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__GRootWriterDictLN_TTree = { "TTree" , 99 , -1 };
G__linked_taginfo G__GRootWriterDictLN_TFile = { "TFile" , 99 , -1 };
G__linked_taginfo G__GRootWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__GRootWriterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__GRootWriterDictLN_ROOTcLcLMath = { "ROOT::Math" , 110 , -1 };
G__linked_taginfo G__GRootWriterDictLN_ROOTcLcLMathcLcLDisplacementVector3DlEROOTcLcLMathcLcLCartesian3DlEdoublegRcOROOTcLcLMathcLcLDefaultCoordinateSystemTaggR = { "ROOT::Math::DisplacementVector3D<ROOT::Math::Cartesian3D<double>,ROOT::Math::DefaultCoordinateSystemTag>" , 99 , -1 };
G__linked_taginfo G__GRootWriterDictLN_GRootWriter = { "GRootWriter" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableGRootWriterDict() {
  G__GRootWriterDictLN_TClass.tagnum = -1 ;
  G__GRootWriterDictLN_TBuffer.tagnum = -1 ;
  G__GRootWriterDictLN_TMemberInspector.tagnum = -1 ;
  G__GRootWriterDictLN_ROOT.tagnum = -1 ;
  G__GRootWriterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR.tagnum = -1 ;
  G__GRootWriterDictLN_string.tagnum = -1 ;
  G__GRootWriterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__GRootWriterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GRootWriterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__GRootWriterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__GRootWriterDictLN_TTree.tagnum = -1 ;
  G__GRootWriterDictLN_TFile.tagnum = -1 ;
  G__GRootWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__GRootWriterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__GRootWriterDictLN_ROOTcLcLMath.tagnum = -1 ;
  G__GRootWriterDictLN_ROOTcLcLMathcLcLDisplacementVector3DlEROOTcLcLMathcLcLCartesian3DlEdoublegRcOROOTcLcLMathcLcLDefaultCoordinateSystemTaggR.tagnum = -1 ;
  G__GRootWriterDictLN_GRootWriter.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableGRootWriterDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__GRootWriterDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__GRootWriterDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__GRootWriterDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__GRootWriterDictLN_ROOT);
   G__get_linked_tagnum_fwd(&G__GRootWriterDictLN_vectorlEfloatcOallocatorlEfloatgRsPgR);
   G__get_linked_tagnum_fwd(&G__GRootWriterDictLN_string);
   G__get_linked_tagnum_fwd(&G__GRootWriterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__GRootWriterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GRootWriterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__GRootWriterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__GRootWriterDictLN_TTree);
   G__get_linked_tagnum_fwd(&G__GRootWriterDictLN_TFile);
   G__get_linked_tagnum_fwd(&G__GRootWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__GRootWriterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__GRootWriterDictLN_ROOTcLcLMath);
   G__get_linked_tagnum_fwd(&G__GRootWriterDictLN_ROOTcLcLMathcLcLDisplacementVector3DlEROOTcLcLMathcLcLCartesian3DlEdoublegRcOROOTcLcLMathcLcLDefaultCoordinateSystemTaggR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__GRootWriterDictLN_GRootWriter),sizeof(GRootWriter),-1,295936,(char*)NULL,G__setup_memvarGRootWriter,G__setup_memfuncGRootWriter);
}
extern "C" void G__cpp_setupGRootWriterDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupGRootWriterDict()");
  G__set_cpp_environmentGRootWriterDict();
  G__cpp_setup_tagtableGRootWriterDict();

  G__cpp_setup_inheritanceGRootWriterDict();

  G__cpp_setup_typetableGRootWriterDict();

  G__cpp_setup_memvarGRootWriterDict();

  G__cpp_setup_memfuncGRootWriterDict();
  G__cpp_setup_globalGRootWriterDict();
  G__cpp_setup_funcGRootWriterDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncGRootWriterDict();
  return;
}
class G__cpp_setup_initGRootWriterDict {
  public:
    G__cpp_setup_initGRootWriterDict() { G__add_setup_func("GRootWriterDict",(G__incsetup)(&G__cpp_setupGRootWriterDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initGRootWriterDict() { G__remove_setup_func("GRootWriterDict"); }
};
G__cpp_setup_initGRootWriterDict G__cpp_setup_initializerGRootWriterDict;

